version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: coffee_db
    restart: always
    environment:
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: coffee_pw
      POSTGRES_DB: coffee
    ports:
      - 5432:5432
    volumes:
      - ./coffee_postgres-data:/var/lib/postgresql/data

volumes:
  coffee_postgres-data: